config/routes.rb
Rails.application.routes.draw do
  resources :exchange_rates
   
  match 'exchange_rates/index' => 'exchange_rates#index', via: [:post, :get]
  
  root 'exchange_rates#index'

end

app/models/concerns/fx/exchange_rate.rb
require 'date'
module  Fx::ExchangeRate
 extend ActiveSupport::Concern
  
 module ClassMethods
  
  def at(date = Date.today, base_currency, counter_currency)
    base =  base_currency.upcase
    counter = counter_currency.upcase
      
    #GBP/GBP
     puts 'calculating base currency rate'
     base(base, date)
    
     puts 'calculating fx rate'
     counter(counter, date)

   end
  
   def counter(counter, date)
     #d =  ExchangeRate.by_currency(counter).by_date(date) 
     d = ExchangeRate.by_currency(counter) 
     e = d.first
     @counter_rate = e.rate.to_f
     @counter_to_base_fx_rate = (@counter_rate / @base_rate).round(4)
    end
  
    def base (base, date)
      puts'from base method'
      a = ExchangeRate.by_currency(base) 
      #a =  EXchangeRate.by_currency(base).by_date(date) 
       b = a.first
       @base_rate = b.rate.to_f
       puts @base_rate
       @base_to_base_fx_rate = ( @base_rate / @base_rate).round(4)
     end
   
     def convert(date, amount, base_currency, counter_currency)
       @rate = at(date, base_currency, counter_currency)
       @converted_amount =  @rate *  amount.to_f
       puts "the converted amount is #{@converted_amount}"
     end
  
  end 
end 

app/models/exchange_rate.rb
class ExchangeRate < ActiveRecord::Base
  include  Fx::ExchangeRate
  attr_accessor :amount, :from_currency, :to_currency
  
  validates :date, :currency, :rate,  presence: true, uniqueness: true
  
  scope :by_date, -> (date) {where("date < ?", date)} 
  scope :by_currency, -> (currency) {where(currency: currency) } 
  scope :by_distinct_currency, -> {ExchangeRate.select("distinct id, currency")}
  scope :by_date_currency, -> {ExchangeRate.select("distinct date, currency")}
  scope :unique_currencies_array, -> {ExchangeRate.uniq.pluck(:currency)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exchange_rates_controller.rb
class ExchangeRatesController < ApplicationController
  
   def index
    @converter = ExchangeRate.all.to_a
   # @currencies = ExchangeRate.by_distinct_currency
    @currenci = ExchangeRate.unique_currencies_array
    
    if params[:date]
      #Converter.convert('2014-05-06', 10, 'gbp', 'dkk')   
      @converted = ExchangeRate.convert(params[:date], params[:amount], params[:from], params[:to])
    end
     puts "display your value #{@converted}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchange_rates_helper.rb
module ExchangeRatesHelper
end

app/views/exchange_rates/index.html.erb
<div class="form-horizontal">

  <% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <%= form_tag(exchange_rates_index_url, :multipart => true, :class => "form") do %>
  
    <fieldset>
    <div class="col-lg-8">
      <div class="form-group">
        <label class="control-label"> <%= label_tag :date, "Date" %></label>
       <div class="form-control">
        <%= text_field_tag :date, params[:date] || Date.today, :placeholder => Date.today %>
         </div>
     </div>
     </div>
      
      <div class="col-lg-8">
      <div class="form-group">
        <label class="control-label"> <%= label_tag :amount, "Amount" %></label>
       <div class="form-control">
         <%= text_field_tag :amount, params[:amount], :placeholder => 100 %>
         </div>
     </div>
     </div>
    
    
    <%= label_tag :from, "From" %>
    <%= select_tag :from, options_for_select(@currenci, params[:from]) %>
      
      
     
    <%= label_tag :to, "To" %>
     <%= select_tag :to, options_for_select(@currenci, params[:to]) %>
       
      
    <br />
    <%= submit_tag "Submit", :class => 'btn' %>
  </fieldset>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fx</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
     
  <div class="container">
    <div class="row">
          
     <%= yield %>
             
      
    </div><!-- /.row -->
  </div><!-- /.container -->

</body>
</html>